### PR TITLE
metadata, references in all tables, comments and markdown parsing

### PR DESCRIPTION
**Pull request by GiacomoPope**
Additionally made an image for the Twitter / link sharing card

### CODE REVIEW

**Comment by GiacomoPope** [comment]
I should do this on issikebrokenyet branches, but I didn't think clearly this morning. This should be the last jack -> isby pull request, then I'll do things internally.

**Comment by GiacomoPope** [comment]
We now have checkboxes which toggle rows filled with comment data.

**Comment by GiacomoPope** [comment]
Ok really gonna stop now. Comments support basic markdown and MathJax

**Comment by defeo** [comment]
Is this ready for merging, or do you plan to commit more here?

**Comment by GiacomoPope** [comment]
I think this is good. Only criticism would be it will leave the tables with many empty cells (those without references or comments) but as far as I can tell this "works as intended"

Edit: didn't merge myself just so you could look it over before it jumped onto main

**Pull request merged**
