### PR TITLE
Include links to references and include basic CSS

### PR DESCRIPTION
**Pull request by GiacomoPope**
* Some whitespace changes to `build.py`
* Included references in `attack.yml` (except Galbraith exp attack, as I wasn't sure which one this was, and MiTM as I wasn't sure which was first)
* Included logic in `build.py` to construct reference links

### CODE REVIEW

**Comment by GiacomoPope** [comment]
Also, could potentially `.gitignore` `index.html` and have this built so it doesn't get passed backwards and forwards. Didn't do this in case you wanted it this way

**Comment by GiacomoPope** [comment]
Also included some lightweight CSS, cleaned up how the type on CSIDH was displayed and fixed some more unicode issues in the yml files.

**Comment by defeo** [comment]
Thank you very much!

Suggestion: make `reference` a list, rather than a single paper. Some attacks may have more than one reference.

I have no strong opinions on anything. Not even on using Python. And I agree we should use CI to push `index.html`, rather than manually committing every time.

Shall I invite you to the org?

**Comment by GiacomoPope** [comment]
Thanks Luca!!

Just modified the structure so we have `references = {slug : reference_url}` via yml, which will allow many references when needed. I also modified the format to include `[XXX00]` to be more standard.

Also some small formatting changes and I removed index.html via git ignore

Lastly, happy to join the org and help out 🐙

**Comment by defeo** [comment]
I'll wait for CI to be set up before merging this. I haven't used GitHub's CI in a while, so I have to relearn it, I'll give it a shot later.

**Pull request merged**
